part1: part1.c
	clang -I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib -lcrypto -o part1 part1.c

part2: part2.c
	clang -O3 -I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib -lcrypto -o part2 part2.c
